--- 

- name: generate random password with constraints
  hosts: localhost
  gather_facts: true
    
  vars:
    password_length: 12
    password_specs:
    - digits
    - ascii_lowercase
    - ascii_uppercase
    - punctuation
  
  tasks:
  
  - name: House keeping stuff
    set_fact:
      remaining_password_length: "{{ password_length -  password_specs | length }}"
      password_spec_str: "{{ password_specs | join(',') }}"  
      
  - name: Generate password with required constraints
    set_fact:
      pwd_pool: "{{ pwd_pool | default([]) + [lookup('password', '/dev/null length=1 chars=' ~item)]}}"
    loop: "{{ password_specs }}"
    
  - name: Create required length of password
    debug:
      msg: "{{ pwd_pool | join('') + lookup('password', '/dev/null length=' ~ remaining_password_length ~ ' chars=' ~ password_spec_str )}}"