--- 

- name: generate random password with constraints
  hosts: localhost
  gather_facts: true
    
  tasks:

  - name: Include pass_vars file
    include_vars: 
      file: password_vars.yml
  
  - name: set facts for random password
    set_fact:
      remaining_password_length: "{{ password_length -  password_specs | length }}"
      password_spec_str: "{{ password_specs | join(',') }}"  
      
  - name: Generate password with required constraints
    set_fact:
      pwd_pool: "{{ pwd_pool | default([]) + [lookup('password', '/dev/null length=1 chars=' ~item)]}}"
    loop: "{{ password_specs }}"
    
  - name: Create required length of password
    debug:
      msg: "{{ pwd_pool | join('') + lookup('password', '/dev/null length=' ~ remaining_password_length ~ ' chars=' ~ password_spec_str )}}"

  - name: create pass_vault.yml file
    copy:
      content: "Vault password:"
      dest: "vars/pass_vault.yml"

  - name: write password to file                                                                              
    blockinfile:
      dest: vars/pass_vault.yml
      marker: ""
      block: |                                                                                             
        my_password: {{ pwd_pool | join('') + lookup('password', '/dev/null length=' ~ remaining_password_length ~ ' chars=' ~ password_spec_str )}}
      insertafter: "Vault password:"
      state: present 

  - name: Remove blank lines blockinfile put in
    lineinfile :
      path: vars/pass_vault.yml
      state: absent
      regexp: '^$'
      