---


- name: example expect module with Ansible
  hosts: localhost
  gather_facts: true

  tasks:

  - name: Test Script
    expect:
      command: ./sc.sh
      responses:
        enter one: 'one'
        enter two: 'two'
        enter three: 'three'
        enter password: 'pass'
      echo: yes